const PRICE_UPDATE_INTERVAL = 5 * 60 * 10 ** 3;
const JWT_REFRESH_INTERVAL = 14 * (60 * 10 ** 3);
const BALANCE_REFRESH_INTERVAL = 30 * 10 ** 3;

export { PRICE_UPDATE_INTERVAL, JWT_REFRESH_INTERVAL, BALANCE_REFRESH_INTERVAL };
