// biome-ignore-all lint: generated by wasm-bindgen
/* tslint:disable */
/* eslint-disable */

export class WasmCircuitProver {
    free(): void;
    [Symbol.dispose](): void;
    constructor(zkey: Uint8Array, expected_zkey_sha256: string, witness_graph: Uint8Array, expected_graph_sha256: string);
    /**
     * Calculate, prove, and self-verify directly from circuit input JSON.
     */
    prove(input_json: string): string;
    readonly numConstraints: number;
    readonly numPublic: number;
}

export class WasmProver {
    free(): void;
    [Symbol.dispose](): void;
    constructor(zkey: Uint8Array, expected_sha256: string);
    /**
     * Return `{"proof": ..., "publicSignals": [...]}` in snarkjs shape.
     */
    prove(wtns: Uint8Array): string;
    readonly numConstraints: number;
    readonly numPublic: number;
}

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_wasmcircuitprover_free: (a: number, b: number) => void;
    readonly __wbg_wasmprover_free: (a: number, b: number) => void;
    readonly wasmcircuitprover_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
    readonly wasmcircuitprover_numConstraints: (a: number) => number;
    readonly wasmcircuitprover_numPublic: (a: number) => number;
    readonly wasmcircuitprover_prove: (a: number, b: number, c: number) => [number, number, number, number];
    readonly wasmprover_new: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly wasmprover_prove: (a: number, b: number, c: number) => [number, number, number, number];
    readonly wasmprover_numConstraints: (a: number) => number;
    readonly wasmprover_numPublic: (a: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
