// ─────────────────────────────────────────────────────────────────────────────
// @0xcurvy/curvy-sdk — functional, framework-agnostic core (viem/wagmi-style).
//
// Create a config once, then call standalone actions:
//   const config = await createCurvyConfig({ environment: "mainnet" });
//   await getBalances();                 // uses the ambient config
//   await login({ signature });          // or pass { config } explicitly
//
// Specialized protocol tooling lives behind deliberate subpaths:
//   import { poseidonHash } from "@0xcurvy/curvy-sdk/utils";
//   import { initCore } from "@0xcurvy/curvy-sdk/rust-core";
// ─────────────────────────────────────────────────────────────────────────────

export { CurvyAccount } from "./account";
// The primary application API. Keep this list explicit: adding a module export
// must not publish a new root API accidentally.
export {
  type AddAccountParameters,
  type AddPartialAccountParameters,
  type AggregateParameters,
  type AggregateRecipientInput,
  type AggregationCostEstimate,
  type AggregatorSubmission,
  addAccount,
  addPartialAccount,
  aggregate,
  type BuildAggregateRequestParameters,
  type BuildWithdrawRequestParameters,
  buildAggregateRequest,
  buildWithdrawRequest,
  type ChainSubmitResult,
  type DirectShieldParameters,
  type DirectShieldPendingNote,
  type DirectShieldResult,
  directShield,
  type EnsResolveCurvyIdParameters,
  type EstimateBridgeParameters,
  type EstimateExternalTransferArgs,
  type EstimateExternalTransferParameters,
  type EstimateExternalTransferResult,
  type EstimateIntentParameters,
  type ExecuteIntentParameters,
  ensResolveCurvyId,
  estimateAggregationCosts,
  estimateBridge,
  estimateExternalTransfer,
  estimateIntent,
  executeIntent,
  type FindOwnedPortalsParameters,
  type FindPortalParameters,
  findOwnedPortals,
  findPortal,
  type GenerateEntryPortalParameters,
  type GenerateExitPortalParameters,
  type GetAccountByIdParameters,
  type GetAccountsParameters,
  type GetActiveAccountIdParameters,
  type GetActiveAccountParameters,
  type GetBabyJubjubPublicKeyParameters,
  type GetBalancesParameters,
  type GetNetworkParameters,
  type GetNetworksParameters,
  type GetPortalRecordsParameters,
  type GetPortalStatusParameters,
  type GetScanProgressParameters,
  type GetSpendWitnessesParameters,
  type GetTransactionHistoryParameters,
  generateEntryPortal,
  generateExitPortal,
  getAccountById,
  getAccounts,
  getActiveAccount,
  getActiveAccountId,
  getBabyJubjubPublicKey,
  getBalances,
  getNetwork,
  getNetworks,
  getPlanSteps,
  getPortalRecords,
  getPortalStatus,
  getScanProgress,
  getSpendWitnesses,
  getTransactionHistory,
  type HasAccountParameters,
  type HasActiveAccountParameters,
  hasAccount,
  hasActiveAccount,
  type LoginParameters,
  type LoginWithPasskeyParameters,
  type LoginWithPrivateKeysParameters,
  type LogoutParameters,
  login,
  loginWithPasskey,
  loginWithPrivateKeys,
  logout,
  off,
  on,
  type PauseBalanceRefreshParameters,
  type ProveAggregationParameters,
  type ProveWithdrawalParameters,
  pauseBalanceRefresh,
  proveAggregation,
  proveWithdrawal,
  type RecoverPortalParameters,
  type RefreshBalancesParameters,
  type RegisterParameters,
  type RegisterWithPasskeyParameters,
  type RegisterWithPrivateKeysParameters,
  type RelaySubmissionParameters,
  type RemoveAccountParameters,
  type ResetStorageParameters,
  type ResolvedNoteWitness,
  type ResolveNoteWitnessParameters,
  type ResumeBalanceRefreshParameters,
  recoverPortal,
  refreshBalances,
  register,
  registerWithPasskey,
  registerWithPrivateKeys,
  relaySubmission,
  removeAccount,
  resetStorage,
  resolveNoteWitness,
  restoreSession,
  resumeBalanceRefresh,
  type SetActiveAccountParameters,
  type SignMessageWithBabyJubjubParameters,
  type SubmitToChainParameters,
  type SubmittableSubmission,
  type SubmitVia,
  type SwitchNetworkEnvironmentParameters,
  type SyncNotesParameters,
  type SyncNotesResult,
  setActiveAccount,
  signMessageWithBabyJubjub,
  submitToChain,
  switchNetworkEnvironment,
  syncNotes,
  type TransactionHistoryItem,
  type TransactionHistoryKind,
  type ValidNotesRootVerifier,
  type WaitForRelayParameters,
  type WatchAccountsParameters,
  type WatchActiveAccountParameters,
  type WatchEnvironmentParameters,
  type WithdrawParameters,
  waitForRelay,
  watchAccounts,
  watchActiveAccount,
  watchEnvironment,
  withdraw,
} from "./actions";
export {
  acceptsPortalShield,
  type CreateBrowserCurvyConfigParameters,
  type CreateCurvyConfigParameters,
  type CreateServerCurvyConfigParameters,
  type CurvyConfig,
  type CurvyState,
  createBrowserCurvyConfig,
  createCurvyConfig,
  createServerCurvyConfig,
  DEFAULT_EXECUTION_POLICY,
  type DirectSubmitter,
  destroyConfig,
  type ExecutionPolicy,
  getActiveNetworks,
  getCurvyConfig,
  getDefaultAggregatorNetwork,
  getEnvironment,
  getProtocol,
  peekCurvyConfig,
  type ScanStatus,
  type SubmissionMode,
  setCurvyConfig,
  type WithConfig,
} from "./config";
export {
  NETWORK_ENVIRONMENT,
  type NETWORK_ENVIRONMENT_VALUES,
  NETWORK_FLAVOUR,
  type NETWORK_FLAVOUR_VALUES,
} from "./constants/networks";
// Contracts used by public config and action extension points.
export type { CoreAdapter } from "./core/types";
export {
  AccountError,
  AggregationOutputTimeoutError,
  AggregatorSubmitError,
  APIError,
  AuthError,
  CommandError,
  CurvyError,
  type CurvyErrorCode,
  FeeEstimateUnavailableError,
  InsufficientBalanceError,
  MissingContractAddressError,
  NetworkError,
  NoActiveAccountError,
  NoCurvyConfigError,
  normalizeCurvyError,
  PlanEstimationError,
  PlanExecutionError,
  PlanWaitTimeoutError,
  RelayError,
  RouteUnavailableError,
  ScanError,
  SpendKeyRequiredError,
  StorageError,
  ViewKeyRequiredError,
} from "./errors";
export type { CurvyEventBus } from "./events/types";
export type { CurvyApiClient } from "./http/types";
// The protocol note value is part of action inputs/outputs. Note synchronization,
// tree state, and witness helpers remain on the explicit `./note` subpath.
export { Note, type NoteParams } from "./note/note";
export type { BabyJubjubPublicKey, FullNoteData, InputNote, NoteOwner, OutputNote } from "./note/types";
export {
  type BaseIntent,
  type CommandData,
  type CommandEstimate,
  type CommandKind,
  type DeliveredPlanValue,
  type DraftCommand,
  type DraftPlan,
  type EstimatedCommand,
  type EstimatedPlan,
  type ExternalTransferIntent,
  type GeneratePlanReturnType,
  type GiftIntentOutput,
  type Intent,
  type IntentEstimation,
  type IntentOutput,
  isPlanFlowControl,
  type Plan,
  type PlanData,
  type PlanEstimation,
  type PlanExecution,
  type PlanFailure,
  type PlanFlowControl,
  type PlanResult,
  type PlanStep,
  type PlanStepKind,
  type PlanSuccess,
  type PlanSuccessfulEstimation,
  type PlanSuccessfulExecution,
  type PlanUnsuccessfulEstimation,
  type PlanUnsuccessfulExecution,
  type PlanValue,
  type PlanWait,
  type PreparedIntent,
  type SendToAnyoneIntent,
  type SwapIntent,
  type TransferIntent,
} from "./planner/types";
export type { SolanaSigner } from "./rpc/solana";
export * as solana from "./solana";
export type {
  AccountStore,
  BalanceStore,
  CurrencyStore,
  CurvyStorage,
  HistoryStore,
  NotesStore,
  PreferenceStore,
  PrivateTokenStore,
  StorageLifecycleStore,
  TransferStore,
} from "./storage/contracts";
export type {
  AbortOptions,
  AccountAddedEvent,
  AccountChangedEvent,
  AccountRemovedEvent,
  AdditionalAccountData,
  AggregationRequest,
  AggregatorAction,
  AggregatorRequestStatus,
  AggregatorSubmissionAction,
  BalanceBreakdown,
  BalanceEntry,
  BalanceRefreshCancelledEvent,
  BalanceRefreshCompleteEvent,
  BalanceRefreshErrorEvent,
  BalanceRefreshProgressEvent,
  BalanceRefreshStartedEvent,
  BasePortalRequest,
  BridgeEstimate,
  BridgeEstimateRequestBody,
  BridgeEstimateReturnType,
  CircuitConfig,
  CommittedLogKind,
  CoreScanReturnType,
  CoreSendReturnType,
  CoreViewerScanReturnType,
  CURVY_EVENTS,
  Currency,
  CurrencyMetadata,
  CurrencyPrice,
  CurvyAccountData,
  CurvyEventType,
  CurvyId,
  CurvyIdDomain,
  CurvyKeyPairs,
  CurvyPrivateKeys,
  CurvyPublicKeys,
  CurvySignatureParameters,
  DeepNonNullable,
  EvmSignatureData,
  EvmSignTypedDataParameters,
  ExtractKeys,
  ExtractValues,
  FeeCollector,
  FinalityPreference,
  GenericBalanceEntry,
  GetAggregatorRequestStatusReturnType,
  GetCurvyIdByOwnerAddressResponse,
  GetCurvyIdByOwnerAddressReturnType,
  GetNetworksReturnType,
  GetPortalRecordsReturnType,
  GetPortalStatusReturnType,
  GetSyncHotBlocksReturnType,
  GetSyncHotMetaReturnType,
  GetSyncMetaReturnType,
  GetSyncNotesReturnType,
  GetSyncNullifiersReturnType,
  GetSyncPendingReturnType,
  GetSyncShardRootsReturnType,
  HexString,
  HotBlockRecord,
  HotNoteState,
  HotNoteStatus,
  HotOverlayReplacement,
  HotSyncState,
  InputFinalityPolicy,
  InsertEntryPortalRequestBody,
  InsertExitPortalRequestBody,
  InsertPortalReturnType,
  IntentDependency,
  JwtRefreshErrorEvent,
  JwtRefreshSuccessEvent,
  LiveShardRecord,
  MatchedPortalRecord,
  Network,
  NetworksWithCurrenciesResponse,
  NotesCheckpoint,
  PaymasterInfo,
  PlanExecutionCompleteEvent,
  PlanExecutionErrorEvent,
  PlanExecutionProgressEvent,
  PlanExecutionStartedEvent,
  PortalPublicKeysInput,
  PortalRecord,
  PortalState,
  PortalStatusResponse,
  Prettify,
  PriceData,
  PricesResponse,
  PrivacyPassChallengeInfo,
  PrivacyPassIssuerDirectory,
  ProtocolConfig,
  ProtocolResponse,
  RefreshOptions,
  RegisterCurvyIdRequestBody,
  RegisterCurvyIdReturnType,
  RelayProofPayload,
  RelaySubmissionKeyMaterial,
  RelaySubmissionStatus,
  RelaySubmitRequestBody,
  RelaySubmitReturnType,
  ResolveCurvyIdReturnType,
  ScanCursors,
  ScanInfo,
  SerializedCurvyAccount,
  SerializedNoteWitness,
  SerializedPendingNote,
  Signature,
  SignatureData,
  StringifyBigInts,
  SubmitAggregationReturnType,
  SubmitWithdrawReturnType,
  SyncCommittedNote,
  SyncHotAnnouncement,
  SyncHotBlock,
  SyncHotCommittedNote,
  SyncHotNullifier,
  SyncNullifierRecord,
  SyncPendingNote,
  TotalBalance,
  TransferAttempt,
  TransferHistoryRecord,
  TransferIntentStatus,
  TransferSettlement,
  Tuple,
  TxHistoryEntry,
  TxHistoryKind,
  UnauthorizedEvent,
  WithdrawRequest,
} from "./types";
export {
  AGGREGATOR_ACTIONS,
  assertCurvyId,
  assertHexString,
  CURVY_EVENT_TYPES,
  isHexString,
  isValidCurvyId,
  isValidCurvyIdDomain,
} from "./types";
